db.action_traces.remove({
    'act.account': {
        $in: [
            "1hello1world",
            "2g1com.x",
            "alert.x",
            "betdiceadmin",
            "betdicealert",
            "blocktwitter",
            "candy.pra",
            "contractbase",
            "ecafofficiel",
            "endlessgame1",
            "eoseosaddddd",
            "eosplayaloud",
            "eospromdress",
            "eospromoter1",
            "experimentms",
            "gameboylucky",
            "gu2tembqgage",
            "lelego.x",
            "message.bank",
            "news.x",
            "rockscissors",
            "watchdoggiee",
            "watchdoggiee",
            "wizznetwork1",
            "yumgamealert"
        ]
    }
})